$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: nvidia-llama3-8b-nim-dp
endpoint_name: nvidia-llama3-8b-nim-ep
model: azureml://registries/NVIDIA-AI-Enterprise-Preview/models/llama3-8b-instruct-nim_a100_1/versions/1
environment_variables:
    NGC_KEY: ngc_key_placeholder
environment: 
  name: image_name_placeholder-env
  image: acr_registry_placeholder.azurecr.io/image_name_placeholder:latest
  inference_config:
      liveness_route:
          path: /v1/health/ready
          port: 8000
      readiness_route:
          path: /v1/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: instance_type_placeholder
instance_count: 1
